services:
  db:
    image: pgvector/pgvector:pg16
    container_name: doxa_db
    environment:
      POSTGRES_DB: doxa_db
      POSTGRES_USER: doxa
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - doxa_data:/var/lib/postgresql/data

volumes:
  doxa_data: